# Generated by Django 5.0.6 on 2024-06-12 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monopoly', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='value',
        ),
        migrations.AlterField(
            model_name='card',
            name='image',
            field=models.ImageField(upload_to='statics/cards/'),
        ),
        migrations.AlterField(
            model_name='card',
            name='image_back',
            field=models.ImageField(blank=True, null=True, upload_to='statics/cards/'),
        ),
    ]
