# Generated by Django 5.0.6 on 2024-06-12 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monopoly', '0002_remove_card_value_alter_card_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='houses',
        ),
        migrations.CreateModel(
            name='OwnedCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mortgaged', models.BooleanField(default=False)),
                ('houses', models.IntegerField(default=0)),
                ('hotel', models.BooleanField(default=False)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monopoly.case')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='ownedCase',
            field=models.ManyToManyField(to='monopoly.ownedcase'),
        ),
    ]
