# Generated by Django 5.0.6 on 2024-11-06 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monopoly', '0003_remove_case_houses_ownedcase_player_ownedcase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='cards',
            field=models.ManyToManyField(blank=True, to='monopoly.card'),
        ),
        migrations.AlterField(
            model_name='player',
            name='ownedCase',
            field=models.ManyToManyField(blank=True, to='monopoly.ownedcase'),
        ),
    ]
