# Generated by Django 5.0.6 on 2024-11-11 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monopoly', '0005_player_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='position',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
