# Generated by Django 5.0.6 on 2024-11-12 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monopoly', '0006_case_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='price_house',
        ),
    ]
