# Generated by Django 5.0.6 on 2024-11-12 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monopoly', '0007_remove_color_price_house'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='owner',
        ),
    ]
