# Generated by Django 5.2.7 on 2025-11-05 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monopoly', '0008_remove_case_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='dice1Values',
            field=models.IntegerField(default=6),
        ),
        migrations.AddField(
            model_name='game',
            name='dice2Values',
            field=models.IntegerField(default=6),
        ),
    ]
