# Generated by Django 5.2.7 on 2025-11-05 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monopoly', '0009_game_dice1values_game_dice2values'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='dice1Values',
            new_name='dice1Value',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='dice2Values',
            new_name='dice2Value',
        ),
    ]
