# Generated by Django 5.2.7 on 2025-11-06 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monopoly', '0010_rename_dice1values_game_dice1value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='has_rolled',
            field=models.BooleanField(default=True),
        ),
    ]
