# Generated by Django 5.2.7 on 2025-11-06 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monopoly', '0011_player_has_rolled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='id',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='id',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
    ]
