# Generated by Django 5.2.7 on 2025-11-07 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monopoly', '0013_alter_game_id_alter_player_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CaseType',
            new_name='SpaceType',
        ),
        migrations.RemoveField(
            model_name='player',
            name='ownedCase',
        ),
        migrations.RenameField(
            model_name='board',
            old_name='cases',
            new_name='spaces',
        ),
        migrations.RenameModel(
            old_name='Case',
            new_name='Space',
        ),
        migrations.CreateModel(
            name='OwnedSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mortgaged', models.BooleanField(default=False)),
                ('houses', models.IntegerField(default=0)),
                ('hotel', models.BooleanField(default=False)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monopoly.space')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='ownedSpace',
            field=models.ManyToManyField(blank=True, to='monopoly.ownedspace'),
        ),
        migrations.DeleteModel(
            name='OwnedCase',
        ),
    ]
