# Generated by Django 5.2.7 on 2025-11-10 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monopoly', '0014_rename_casetype_spacetype_remove_player_ownedcase_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ownedspace',
            old_name='hotel',
            new_name='has_hotel',
        ),
        migrations.RenameField(
            model_name='ownedspace',
            old_name='mortgaged',
            new_name='is_mortgaged',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='ownedSpace',
            new_name='owned_space',
        ),
    ]
