# Generated by Django 5.2.7 on 2025-11-10 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monopoly', '0015_rename_hotel_ownedspace_has_hotel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='owned_space',
            new_name='owned_spaces',
        ),
    ]
