# Generated by Django 5.2.8 on 2025-11-12 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monopoly', '0016_rename_owned_space_player_owned_spaces'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='start_gain_amount',
            field=models.IntegerField(default=200),
        ),
    ]
