# Generated by Django 5.2.8 on 2025-11-12 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monopoly', '0017_game_start_gain_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='players',
        ),
        migrations.AddField(
            model_name='player',
            name='game',
            field=models.ForeignKey(default='d13d68cb2e3e4ca1a5727ee6530ebd3f', on_delete=django.db.models.deletion.CASCADE, related_name='players', to='monopoly.game'),
            preserve_default=False,
        ),
    ]
