# Generated by Django 5.2.8 on 2025-11-12 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monopoly', '0018_remove_game_players_player_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='jail_fee_amount',
            field=models.IntegerField(default=50),
        ),
    ]
