# Generated by Django 5.2.8 on 2025-11-12 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monopoly', '0019_game_jail_fee_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='nb_double_rolls',
            field=models.IntegerField(default=0),
        ),
    ]
