# Generated by Django 5.2.8 on 2025-11-12 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monopoly', '0020_player_nb_double_rolls'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='owned_spaces',
        ),
        migrations.AddField(
            model_name='ownedspace',
            name='player',
            field=models.ForeignKey(default='98f509be1d0542759b8262c645871ff9', on_delete=django.db.models.deletion.CASCADE, related_name='owned_spaces', to='monopoly.player'),
            preserve_default=False,
        ),
    ]
