# Generated by Django 5.2.8 on 2025-11-12 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monopoly', '0021_remove_player_owned_spaces_ownedspace_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='nb_spaces',
            field=models.IntegerField(default=3),
        ),
    ]
